/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_sportscience;

/**
 *
 * @author arfan
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jbt_regis = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_loginatlet = new javax.swing.JButton();
        btn_loginpelatih = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bckground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBackground(new java.awt.Color(248, 248, 248));
        txt_username.setBorder(null);
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 260, 20));

        txt_password.setBackground(new java.awt.Color(248, 248, 248));
        txt_password.setBorder(null);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 250, 20));

        jbt_regis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbt_regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_regisMouseClicked(evt);
            }
        });
        getContentPane().add(jbt_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 60, 10));

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        btn_loginatlet.setText("Atlet");
        btn_loginatlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginatletActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loginatlet);

        btn_loginpelatih.setText("Pelatih");
        btn_loginpelatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginpelatihActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loginpelatih);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 210, 40));

        jLabel1.setText("Login Sebagai:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        bckground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_sportscience/image/loginform.jpg"))); // NOI18N
        getContentPane().add(bckground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_regisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_regisMouseClicked
        // TODO add your handling code here:
        new register().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_regisMouseClicked

    private void btn_loginatletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginatletActionPerformed
          // TODO add your handling code here:
        try{
            String sql= "SELECT * FROM akun_atlet WHERE username_atlet='"+txt_username.getText()+ "'AND password_atlet='"+ txt_password.getText()+"'";
            Connection con=(Connection)koneksi.koneksiDB();
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery(sql);
            if (rs.next()){
               if (txt_username.getText().equals(rs.getString("username_atlet"))
                       && txt_password.getText().equals(rs.getString("password_atlet"))) {
                   JOptionPane.showMessageDialog(null, " Berhasil Login");
                   menu1_atlet.txt_idatlet1.setText(rs.getString("id_atlet"));
                   menu1_atlet.lbl_idatlet.setText(rs.getString(1));
                   menu1_atlet.lbl_namaatlet.setText(rs.getString(2));
                   menu1_atlet.lbl_alamatatlet.setText(rs.getString(3));
                   menu1_atlet.lbl_notelp.setText(rs.getString(4));
                   this.setVisible(false);
                   new menu1_atlet().setVisible(true);
               }
            } 
            else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }
            
        }
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_btn_loginatletActionPerformed

    private void btn_loginpelatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginpelatihActionPerformed
        // TODO add your handling code here:
         try{
            String sql= "SELECT * FROM akun_pelatih WHERE username_pelatih='"+txt_username.getText()+ "'AND password_pelatih='"+ txt_password.getText()+"'";
            Connection con=(Connection)koneksi.koneksiDB();
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery(sql);
            if (rs.next()){
               if (txt_username.getText().equals(rs.getString("username_pelatih"))
                       && txt_password.getText().equals(rs.getString("password_pelatih"))) {
                   JOptionPane.showMessageDialog(null, " Berhasil Login");
                   menu1_pelatih.lbl_idpelatih.setText(rs.getString(1));
                   menu1_pelatih.lbl_namapelatih.setText(rs.getString(2));
                   menu1_pelatih.lbl_alamatpelatih.setText(rs.getString(3));
                   menu1_pelatih.lbl_notelp.setText(rs.getString(4));
                   this.setVisible(false);
                   new menu1_pelatih().setVisible(true);
               }
            } 
            else {
                JOptionPane.showMessageDialog(null, "username atau password salah");
            }
            
        }
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_btn_loginpelatihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckground;
    private javax.swing.JButton btn_loginatlet;
    private javax.swing.JButton btn_loginpelatih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jbt_regis;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
