/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_sportscience;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arfan
 */
public class menu1_pelatih extends javax.swing.JFrame {

    /**
     * Creates new form menu1_pelatih
     */
    public menu1_pelatih() {
        initComponents();
        tampilkan_data();
        resetautoincrement();
        
    }
    
    
     private void resetautoincrement(){
        try {
            String sql1 = "ALTER TABLE akun_atlet AUTO_INCREMENT=1";
            String sql2 = "ALTER TABLE akun_pelatih AUTO_INCREMENT=1";
            String sql3 = "ALTER TABLE datalatihan_atlet AUTO_INCREMENT=1";
            
            Connection con = (Connection)koneksi.koneksiDB();
            PreparedStatement pst1 = con.prepareStatement(sql1);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            PreparedStatement pst3 = con.prepareStatement(sql3);
          
            pst1.execute();
            pst2.execute();
            pst3.execute();     
            
        } 
        catch (Exception e) {
        }
    }
    
    
    public void tampilkan_data(){
        
   
    DefaultTableModel model = new DefaultTableModel();
    
    model.addColumn("ID");
    model.addColumn("Nama Atlet");
    model.addColumn("Alamat");
    model.addColumn("No Telp");
    tbl_data.setModel(model);
    
    try{
        int no=1;
        String sql = "SELECT * FROM akun_atlet";
        java.sql.Connection con = (Connection) koneksi.koneksiDB();
        java.sql.Statement stm = con.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()){
            model.addRow(new Object[]{
            res.getString("id_atlet"),
            res.getString("nama_atlet"),
            res.getString("alamat_atlet"),
            res.getString("notelp_atlet"),
            
            });
           
           
        
        }
        
    }catch(SQLException e){
       JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan" + e.getMessage());
    }
    
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jbtn_feedback = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        bckgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 253, 253));
        jLabel2.setText("Informasi Atlet");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 170, 20));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_data);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 540, 360));

        jbtn_feedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_feedbackMouseClicked(evt);
            }
        });
        getContentPane().add(jbtn_feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 20));

        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 464, 100, 20));

        id.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 0, 0));
        id.setText("ID:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 10));

        lbl_namapelatih.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lbl_namapelatih.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_namapelatih, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 20));

        lbl_idpelatih.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_idpelatih.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_idpelatih, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 10));

        lbl_alamatpelatih.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_alamatpelatih.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_alamatpelatih, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 10));

        lbl_notelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_notelp.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 10));

        bckgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_sportscience/image/menu1_pelatih.jpg"))); // NOI18N
        getContentPane().add(bckgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void jbtn_feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_feedbackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
                   new menu2_pelatih().setVisible(true);
    }//GEN-LAST:event_jbtn_feedbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu1_pelatih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu1_pelatih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu1_pelatih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu1_pelatih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu1_pelatih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckgrnd;
    private javax.swing.JLabel btn_logout;
    public static final javax.swing.JLabel id = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbtn_feedback;
    public static final javax.swing.JLabel lbl_alamatpelatih = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_idpelatih = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_namapelatih = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_notelp = new javax.swing.JLabel();
    private javax.swing.JTable tbl_data;
    // End of variables declaration//GEN-END:variables
}
