/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_sportscience;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author arfan
 */
public class menu1_atlet extends javax.swing.JFrame {
    PreparedStatement pst;
    ResultSet res;
    
    
    private String tgl;
    int a;

    /**
     * Creates new form menu1_atlet
     */
    public menu1_atlet() {
        initComponents();
        loadData();
        tampil_jumlahtend();
        //tampil_id();
        resetautoincrement();
    }
    
    
     private void resetautoincrement(){
        try {
            String sql1 = "ALTER TABLE akun_atlet AUTO_INCREMENT=1";
            String sql2 = "ALTER TABLE akun_pelatih AUTO_INCREMENT=1";
            String sql3 = "ALTER TABLE datalatihan_atlet AUTO_INCREMENT=1";
            
            Connection con = (Connection)koneksi.koneksiDB();
            PreparedStatement pst1 = con.prepareStatement(sql1);
            PreparedStatement pst2 = con.prepareStatement(sql2);
            PreparedStatement pst3 = con.prepareStatement(sql3);
          
            pst1.execute();
            pst2.execute();
            pst3.execute();     
        } 
        catch (Exception e) {
        }
    }
    
    
    private void loadData(){
        try {
            String sql = "select * from tb_alat";
            Connection con = (Connection)koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
        while (res.next()){
            System.out.println(dataKeep.convert);
            a = res.getInt("tendangan") - dataKeep.convert;
            tampil_tndngan.setText(Integer.toString(a));
        }    
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data");
        }
    }
    
    
    
    private void tmbhdata(){
        try {
            
         String sql = "INSERT INTO datalatihan_atlet (id_data, id_atlet,tanggal,jml_tendangan,evaluasi) VALUES (null,'"+txt_idatlet1.getText()+"','"
                 +tgl+"','"+a+"', '')";
         String sql1 = "ALTER TABLE datalatihan_atlet AUTO_INCREMENT=1";
         Connection con=(Connection)koneksi.koneksiDB();
         PreparedStatement pst = con.prepareStatement(sql);
         PreparedStatement pst1 = con.prepareStatement(sql1);
         
         pst.execute();
         pst1.execute();
    
         JOptionPane.showMessageDialog(null, "Data berhasil ditambah");
        } 
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void tampil_jumlahtend(){
            try {
                String sql = "SELECT * FROM tb_alat";
            Connection con = (Connection)koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
              while(res.next()){
                  txt_jumlah.setText(res.getString("tendangan"));
                  
              }  
            } catch (Exception e) {
            }
    }
    
    private void tampil_id(){
         try {
                String sql = "SELECT * FROM akun_atlet";
            Connection con = (Connection)koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
              while(res.next()){
                  txt_idatlet1.setText(res.getString("id_atlet"));
                  
              }  
            } catch (Exception e) {
            }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanggal = new com.toedter.calendar.JDateChooser();
        jbtn_datalatihan = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        btn_ulangi = new javax.swing.JLabel();
        tampil_tndngan = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_simpan1 = new javax.swing.JLabel();
        bckgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 200, 40));

        jbtn_datalatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_datalatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_datalatihanMouseClicked(evt);
            }
        });
        getContentPane().add(jbtn_datalatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 20));

        lbl_namaatlet.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lbl_namaatlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_namaatlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, 20));

        lbl_idatlet.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_idatlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_idatlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, 10));

        lbl_alamatatlet.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_alamatatlet.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_alamatatlet, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 10));

        lbl_notelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        lbl_notelp.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 10));

        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 464, 100, 20));

        btn_ulangi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ulangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ulangiMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ulangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 110, 20));

        id.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("ID:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, 10));

        tampil_tndngan.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        tampil_tndngan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tampil_tndngan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 110, 70));

        btn_refresh.setBackground(new java.awt.Color(255, 51, 51));
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 90, 30));

        btn_simpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpan1MouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 100, 20));

        txt_idatlet1.setEditable(false);
        txt_idatlet1.setBackground(new java.awt.Color(255, 255, 255));
        txt_idatlet1.setBorder(null);
        txt_idatlet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idatlet1ActionPerformed(evt);
            }
        });
        txt_idatlet1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_idatlet1PropertyChange(evt);
            }
        });
        getContentPane().add(txt_idatlet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 30, -1));

        txt_jumlah.setEditable(false);
        txt_jumlah.setBackground(new java.awt.Color(255, 252, 252));
        txt_jumlah.setBorder(null);
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_jumlahPropertyChange(evt);
            }
        });
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 40, -1));

        bckgrond.setForeground(new java.awt.Color(255, 255, 255));
        bckgrond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_sportscience/image/menulatihanatlet.jpg"))); // NOI18N
        getContentPane().add(bckgrond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_datalatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_datalatihanMouseClicked
   // TODO add your handling code here:
         try{
            String sql= "SELECT * FROM akun_atlet";
            Connection con=(Connection)koneksi.koneksiDB();
            PreparedStatement pst= con.prepareStatement(sql);
            ResultSet rs= pst.executeQuery(sql);
            if (rs.next()){
             
        this.setVisible(false);
                   new menu2_atlet().setVisible(true);
               }
            } catch (SQLException ex) {
            Logger.getLogger(menu1_atlet.class.getName()).log(Level.SEVERE, null, ex);
        }
                     
        
         
               
    }//GEN-LAST:event_jbtn_datalatihanMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        /* String jumlah="";
        jumlah  = txt_jumlah.getText();
        
        dataKeep.convert = Integer.parseInt(jumlah);
        
         try {
              String sql = "DELETE FROM tb_alat";
              String sql1 = "ALTER TABLE tb_alat AUTO_INCREMENT=1";
              
         Connection con=(Connection)koneksi.koneksiDB();
         PreparedStatement pst = con.prepareStatement(sql);
         PreparedStatement pst1 = con.prepareStatement(sql1);
         pst.execute();
         pst1.execute();
         
         } catch (Exception e) {
            e.printStackTrace();
        }*/
        
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_ulangiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ulangiMouseClicked
        // TODO add your handling code here:
        String jumlah="";
        jumlah  = txt_jumlah.getText();
        
        dataKeep.convert = Integer.parseInt(jumlah);
        
        try {
              String sql = "DELETE FROM tb_alat";
              String sql1 = "ALTER TABLE tb_alat AUTO_INCREMENT=1";
              
         Connection con=(Connection)koneksi.koneksiDB();
         PreparedStatement pst = con.prepareStatement(sql);
         PreparedStatement pst1 = con.prepareStatement(sql1);
         pst.execute();
         pst1.execute();
         
        tanggal.setDateFormatString("");
        
        txt_jumlah.setText("");
         
          JOptionPane.showMessageDialog(null, "Data Berhasil Di Reset");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_ulangiMouseClicked

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
        if(tanggal.getDate()!=null){
            SimpleDateFormat format_tanggal = new SimpleDateFormat("yyyy-MM-dd");
            tgl = format_tanggal.format(tanggal.getDate());
        }
    }//GEN-LAST:event_tanggalPropertyChange

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu1_atlet().setVisible(true);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_simpan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpan1MouseClicked
        // TODO add your handling code here:
        tmbhdata();
    }//GEN-LAST:event_btn_simpan1MouseClicked

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_jumlahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_jumlahPropertyChange

        txt_jumlah.setVisible(false);
    }//GEN-LAST:event_txt_jumlahPropertyChange

    private void txt_idatlet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idatlet1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_idatlet1ActionPerformed

    private void txt_idatlet1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_idatlet1PropertyChange
        // TODO add your handling code here:
        txt_idatlet1.setVisible(false);
    }//GEN-LAST:event_txt_idatlet1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu1_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu1_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu1_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu1_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu1_atlet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckgrond;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel btn_simpan1;
    private javax.swing.JLabel btn_ulangi;
    public static final javax.swing.JLabel id = new javax.swing.JLabel();
    private javax.swing.JLabel jbtn_datalatihan;
    public static final javax.swing.JLabel lbl_alamatatlet = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_idatlet = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_namaatlet = new javax.swing.JLabel();
    public static final javax.swing.JLabel lbl_notelp = new javax.swing.JLabel();
    private javax.swing.JLabel tampil_tndngan;
    private com.toedter.calendar.JDateChooser tanggal;
    public static final javax.swing.JTextField txt_idatlet1 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txt_jumlah = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
