/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_sportscience;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.net.URI;
import java.net.URL;
import static program_sportscience.menu1_atlet.txt_jumlah;

/**
 *
 * @author arfan
 */
public class menu2_atlet extends javax.swing.JFrame {

    /**
     * Creates new form menu2_atlet
     */
    public menu2_atlet() {
        initComponents();
        loadtable();
        
        

    }
     private void loadtable(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Data");
        model.addColumn("ID Atlet");
        model.addColumn("Tanggal");
        model.addColumn("Jumlah Tendangan");
        model.addColumn("Evaluasi"); 
        
        try {
            String sql = "SELECT `id_data`, `id_atlet`, `tanggal`, `jml_tendangan`, `evaluasi` FROM `datalatihan_atlet`";
            Connection con = (Connection)koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{
                   res.getString(1),
                   res.getString(2),
                   res.getString(3),
                   res.getString(4),
                   res.getString(5),
                   
                });
                jTable1.setModel(model);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtn_mulailatihan = new javax.swing.JLabel();
        txt_evaluasi = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        bckgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 560, 360));

        jbtn_mulailatihan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_mulailatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_mulailatihanMouseClicked(evt);
            }
        });
        getContentPane().add(jbtn_mulailatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 20));

        txt_evaluasi.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        txt_evaluasi.setForeground(new java.awt.Color(234, 69, 76));
        txt_evaluasi.setText("Riwayat Latihan");
        getContentPane().add(txt_evaluasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 464, 100, 20));

        bckgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_sportscience/image/m2_atlet.jpg"))); // NOI18N
        getContentPane().add(bckgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_mulailatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_mulailatihanMouseClicked
        // TODO add your handling code here:
        new menu1_atlet().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtn_mulailatihanMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2_atlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu2_atlet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bckgrnd;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jbtn_mulailatihan;
    private javax.swing.JLabel txt_evaluasi;
    // End of variables declaration//GEN-END:variables
}
